-- Generated by nwg-displays on 2026-06-06 at 12:47:29. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "2560x1440@99.95",
    position = "2560x0",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@180.0",
    position = "4000x929",
    scale = 1.0
})
